services:
  db:
    image: postgres:17
    container_name: organization_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: organization_directory_api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8080:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
